/**
 * Base class for every Ziro AI SDK error. Always check with `isZiroError()` —
 * never `instanceof` across realms (e.g. workers, vm contexts).
 */
export class ZiroError extends Error {
  override readonly name: string = 'ZiroError';
  readonly code: string;
  override readonly cause?: unknown;

  constructor(message: string, options: { code: string; cause?: unknown }) {
    super(message);
    this.code = options.code;
    if (options.cause !== undefined) {
      this.cause = options.cause;
    }
    Object.setPrototypeOf(this, new.target.prototype);
  }
}

const ZIRO_ERROR_BRAND = '__ziro_error__';

export function isZiroError(value: unknown): value is ZiroError {
  return (
    typeof value === 'object' &&
    value !== null &&
    (value as { [ZIRO_ERROR_BRAND]?: boolean })[ZIRO_ERROR_BRAND] === true
  );
}

function brand<T extends ZiroError>(err: T): T {
  Object.defineProperty(err, ZIRO_ERROR_BRAND, { value: true, enumerable: false });
  return err;
}

export class APICallError extends ZiroError {
  override readonly name = 'APICallError';
  readonly statusCode?: number;
  readonly url?: string;
  readonly responseBody?: string;
  readonly isRetryable: boolean;

  constructor(options: {
    message: string;
    url?: string;
    statusCode?: number;
    responseBody?: string;
    isRetryable?: boolean;
    cause?: unknown;
  }) {
    super(options.message, { code: 'api_call_error', cause: options.cause });
    if (options.statusCode !== undefined) this.statusCode = options.statusCode;
    if (options.url !== undefined) this.url = options.url;
    if (options.responseBody !== undefined) this.responseBody = options.responseBody;
    this.isRetryable = options.isRetryable ?? defaultIsRetryable(options.statusCode);
    brand(this);
  }
}

function defaultIsRetryable(status: number | undefined): boolean {
  if (status === undefined) return true;
  if (status === 408 || status === 409 || status === 429) return true;
  return status >= 500 && status < 600;
}

export class InvalidPromptError extends ZiroError {
  override readonly name = 'InvalidPromptError';
  constructor(message: string, cause?: unknown) {
    super(message, { code: 'invalid_prompt', cause });
    brand(this);
  }
}

export class InvalidArgumentError extends ZiroError {
  override readonly name = 'InvalidArgumentError';
  readonly argument: string;
  constructor(options: { argument: string; message: string; cause?: unknown }) {
    super(options.message, { code: 'invalid_argument', cause: options.cause });
    this.argument = options.argument;
    brand(this);
  }
}

export class NoTextGeneratedError extends ZiroError {
  override readonly name = 'NoTextGeneratedError';
  constructor() {
    super('No text was generated by the model.', { code: 'no_text_generated' });
    brand(this);
  }
}

export class JSONParseError extends ZiroError {
  override readonly name = 'JSONParseError';
  readonly text: string;
  constructor(text: string, cause?: unknown) {
    super('Failed to parse JSON response from model.', { code: 'json_parse_error', cause });
    this.text = text;
    brand(this);
  }
}

export class TimeoutError extends ZiroError {
  override readonly name = 'TimeoutError';
  readonly timeoutMs: number;
  constructor(timeoutMs: number) {
    super(`Operation timed out after ${timeoutMs}ms.`, { code: 'timeout' });
    this.timeoutMs = timeoutMs;
    brand(this);
  }
}
